core/urls.py
from django.urls import path,include

from . import views
urlpatterns = [
   path('', views.home.as_view(),name='home'),
   path('brandFitering/<slug:brand_slug>/', views.brandFitering,name='brand_slug'),
]

transcation/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('deposite/', views.DepositMoneyView.as_view(),name='deposit'),
    path('borrow/<int:id>/', views.BorrowBook, name='borrow'),
    path('return/<int:id>/', views.returnBook,name='return'),
    path('borrowReport/', views.TransacationReport.as_view(), name='transation'),
   
]

transcation/models.py
from django.db import models
from .constant import TRANSACTION_TYPE
from user_account.models import Useraccount
from django.contrib.auth.models import User
from post.models import PostModel


# ---------------------- Transaction here ---------------------->
class Transcation(models.Model):
    account = models.ForeignKey(
        Useraccount, on_delete=models.CASCADE, related_name="transactions"
    )
    amount = models.DecimalField(decimal_places=2, max_digits=12)
    balance_after_transaction = models.DecimalField(decimal_places=2, max_digits=12)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null=True)


class BorrowedBookModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    borrowed_date = models.DateTimeField(auto_now_add=True)


class review(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.TextField()

transcation/forms.py
from django import forms
from .models import Transcation,review


class TranscationForm(forms.ModelForm):
    class Meta:
        model = Transcation
        fields = ["amount", "transaction_type"]

    def __init__(self, *args, **kwargs):
        self.user_account = kwargs.pop("account")  
        super().__init__(*args, **kwargs)
        self.fields["transaction_type"].disabled = True  #
        self.fields[
            "transaction_type"
        ].widget = forms.HiddenInput()  

    def save(self, commit=True):
        self.instance.account = self.user_account
        self.instance.balance_after_transaction = self.user_account.balance
        return super().save()

class DepositForm(TranscationForm):
    def clean_amount(self): 
        min_deposit_amount = 100
        amount = self.cleaned_data.get('amount') 
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least {min_deposit_amount} $'
            )

        return amount



#----------------------- review --------------------->

class reviewForm(forms.ModelForm):
    class Meta:
        model = review
        fields = ['comment']

transcation/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, View
from .models import Transcation
from .forms import TranscationForm,reviewForm
from .constant import DEPOSIT, BORROW_BOOK
from post.models import PostModel
from django.shortcuts import render, redirect, get_object_or_404
from .models import BorrowedBookModel
from django.urls import reverse
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from user_account.views import send_email

#--------------------------- TransactionCreateMixi ---------------------->
class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = "deposit.html"
    model = Transcation
    title = ""
    success_url = reverse_lazy("home")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"account": self.request.user.account})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"title": self.title})

        return context


#--------------------------send email funciton --------------------------->
def d_send_email(user,template,subject,amount):
    message = render_to_string(template,{
        'user':user,
            'amount':amount,
        })
    send_mail = EmailMultiAlternatives(subject,"",to=[user.email])
    send_mail.attach_alternative(message,'text/html')
    send_mail.send()
#--------------------------- DepositMoneyView ---------------------->
class DepositMoneyView(TransactionCreateMixin):
    form_class = TranscationForm
    title = "Deposit Form"

    def get_initial(self):
        initial = {"transaction_type": DEPOSIT}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get("amount")
        account = self.request.user.account
        account.balance += amount
        account.save(update_fields=["balance"])

        messages.success(
            self.request,
            f'{"{:,.2f}".format(float(amount))}$ was deposited to your account successfully',
        )

        d_send_email(self.request.user,'d.html','Deposite Book Shop',amount)
        return super().form_valid(form)




#--------------------------- BorrowBook ---------------------->
def BorrowBook(request, id):
    book = get_object_or_404(PostModel, pk=id)

    user_balance = int(request.user.account.balance)
    book_price = int(book.borrowed_price)

    if user_balance >= book_price:
        BorrowedBookModel.objects.create(user=request.user, book=book)

        request.user.account.balance -= book_price
        request.user.account.save()
        messages.success(request, "Borrow Book Successfully Now !")
        send_email(request.user, "borrow.html", "Borrow A book in Book Shop")
    return redirect("home")



#--------------------------- returnBook ---------------------->
def returnBook(request, id):
    borrowed_book = get_object_or_404(BorrowedBookModel, pk=id, user=request.user)
    book_price = int(borrowed_book.book.borrowed_price)
    request.user.account.balance += book_price
    request.user.account.save()
    borrowed_book.delete()
    messages.success(request, "Book returned successfully!")
    send_email(request.user, 'return.html', 'Returned a book in Book Shop')
    return redirect("home")




#--------------------------- TransacationReport ---------------------->
class TransacationReport(LoginRequiredMixin, ListView):
    template_name = "transaction.html"
    model = Transcation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"account": self.request.user.account})
        context["transcation"] = Transcation.objects.filter(
            account=self.request.user.account
        )

        return context

transcation/templates/borrow.html
<p>Welcome {{user.first_name}} in HorekRokom Book Shop</p>
<p>Congrations,Book Borrow In Successfully !</p>
<p>HorekRokom Book Shop .............</p>

transcation/templates/d.html
<p> Welcome {{user.first_name}} in HorekRokom Book Shop </P>
    <p>Congrations Your Deposite Successfully , Amount {{amount}} current balance {{user.balance}}</p>
    <p>HorekRokom Book Shop .............</p>

transcation/templates/deposit.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %}
{% block content %}

<div class=" w-100 d-flex justify-content-center  mt-5">
    <div class="shadow w-50  rounded">
        {% if title == 'Request of Loan' %}
        <div><a class="ms-4 mt-4 text-decoration-none text-dark fw-bold" href="{%url 'list'%}">View All Loan
            List</a></div>
        {% endif %}

        <h1 class="font-bold fs-1 text-center pb-5 pt-10 px-5">
            {{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            <div class="mb-4">
                <label style="margin-left: 40%;" class=" fw-bolder mb-4" for="amount">
                    Amount
                </label>
                <input class="shadow form-control m-auto w-50" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <button style="margin-left:30%;"
                    class="btn btn-success px-5"
                    type="submit">
                    Submit
                </button>
        </form>
    </div>

</div>
{% endblock %}

transcation/templates/return.html
<p>Welcome {{user.first_name}} in HorekRokom Book Shop</p>
<p>Thank you for returning the book</p>
<p>HorekRokom Book Shop .............</p>

transcation/templates/transaction.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="mb-5">
    <h1 class="fw-bold fs-1 text-center pb-5 pt-2">Borrowed Report</h1>
    <hr />
    <table class="table-auto mx-auto w-75 shadow rounded px-5 mt-5">
        <thead class="bg-success text-white text-left">
            <tr class="rounded p-5 text-light fw-bold">
                <th class="px-4 py-2">Id</th>
                <th class="px-4 py-2">Transaction type</th>
                <th class="px-4 py-2">Amount</th>
                <th class="px-4 py-2">Balance After Transaction</th>
            </tr>
        </thead>
        <tbody>
            {% for i in transcation %}
            <tr>
                <td class="px-4 py-2">{{ i.id }}</td>
                <td class="px-4 py-2">{{ i.get_transaction_type_display }}</td>
                <td class="px-4 py-2">${{ i.amount }}</td>
                <td class="px-4 py-2">${{ i.balance_after_transaction }}</td>
            </tr>

            {% endfor %}

            <tr class="bg-primary text-white">
                <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
                <th class="px-4 py-2 text-left">$ {{ account.balance }}</th>
            </tr>

            
        </tbody>
    </table>






    
</div>
{% endblock %}